<?php

declare(strict_types=1);

namespace Ddd\Infrastructure\Persistence\Eloquent\Mappers;

use App\Models\User as EloquentUser;
use Ddd\Domain\User\Entities\User;
use Ddd\Domain\User\ValueObjects\Email;
use Ddd\Domain\User\ValueObjects\UserId;

final class UserMapper
{
    /**
     * Convert Eloquent Model to Domain Entity.
     */
    public function toEntity(EloquentUser $model): User
    {
        // Use reflection to bypass private constructor
        $reflection = new \ReflectionClass(User::class);
        $entity = $reflection->newInstanceWithoutConstructor();

        // Set private properties using reflection
        $idProperty = $reflection->getProperty('id');
        $idProperty->setValue($entity, UserId::fromInt((int) $model->id));

        $emailProperty = $reflection->getProperty('email');
        $emailProperty->setValue($entity, Email::fromString($model->email));

        $nameProperty = $reflection->getProperty('name');
        $nameProperty->setValue($entity, $model->name);

        $registeredAtProperty = $reflection->getProperty('registeredAt');
        $registeredAtProperty->setValue($entity, $model->created_at);

        return $entity;
    }

    /**
     * Convert Domain Entity to Eloquent Model.
     */
    public function toModel(User $entity, EloquentUser $model): void
    {
        // Only set ID if entity has one (for updates)
        // For new entities, ID will be auto-generated by database
        try {
            $model->id = $entity->id()->value();
        } catch (\RuntimeException $e) {
            // Entity doesn't have ID yet (new entity) - skip ID assignment
        }

        $model->email = $entity->email()->value();
        $model->name = $entity->name();
        $model->created_at = $entity->registeredAt();
    }
}
