<?php

declare(strict_types=1);

namespace Ddd\Infrastructure\Persistence\Eloquent\Repositories;

use App\Models\User as EloquentUser;
use Ddd\Domain\User\Entities\User;
use Ddd\Domain\User\Repositories\UserRepository;
use Ddd\Domain\User\ValueObjects\Email;
use Ddd\Domain\User\ValueObjects\UserId;
use Ddd\Infrastructure\Persistence\Eloquent\Mappers\UserMapper;

final readonly class EloquentUserRepository implements UserRepository
{
    public function __construct(
        private UserMapper $mapper
    ) {}

    /**
     * Generate next user ID (temporary placeholder for auto-increment)
     *
     * Changed from UUID generation to temporary placeholder ID for bigint primary key migration (Issue #100).
     * For auto-increment IDs, the actual ID is generated by the database on save().
     * This method returns a temporary placeholder ID that will be replaced by the database.
     */
    public function nextId(): UserId
    {
        // Return temporary ID (-1) as placeholder
        // The actual ID will be assigned by the database on save()
        return UserId::fromInt(PHP_INT_MAX);
    }

    public function find(UserId $id): ?User
    {
        $model = EloquentUser::find($id->value());

        return $model ? $this->mapper->toEntity($model) : null;
    }

    public function findByEmail(Email $email): ?User
    {
        $model = EloquentUser::where('email', $email->value())->first();

        return $model ? $this->mapper->toEntity($model) : null;
    }

    public function existsByEmail(Email $email): bool
    {
        return EloquentUser::where('email', $email->value())->exists();
    }

    public function save(User $user): void
    {
        $model = EloquentUser::findOrNew($user->id()->value());
        $this->mapper->toModel($user, $model);
        $model->save();
    }

    public function delete(UserId $id): void
    {
        EloquentUser::destroy($id->value());
    }
}
