name: Frontend Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - 'test-utils/**'
      - 'jest.base.js'
      - 'jest.config.js'
      - 'jest.setup.ts'
      - 'tsconfig.test.json'
      - '.github/workflows/frontend-test.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'test-utils/**'
      - 'jest.base.js'
      - 'jest.config.js'
      - 'jest.setup.ts'
      - 'tsconfig.test.json'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HUSKY: 0

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        app: [admin-app, user-app]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            node_modules
            frontend/${{ matrix.app }}/node_modules
          key: ${{ runner.os }}-npm-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.node-version }}-
            ${{ runner.os }}-npm-

      - name: Install root dependencies
        run: npm ci

      - name: Install ${{ matrix.app }} dependencies
        run: npm ci
        working-directory: frontend/${{ matrix.app }}

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false --maxWorkers=2
        working-directory: frontend/${{ matrix.app }}
        env:
          CI: true

      - name: Archive coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.app }}-node${{ matrix.node-version }}
          path: frontend/${{ matrix.app }}/coverage/
          retention-days: 7
